const A=(q,o,a,e)=>({q,o,a,e:e||`A alternativa ${a} expressa corretamente o conceito cobrado nesta questão.`});
const SIMULADOS=[
{title:'Simulado 1',questions:[
A('Qual conceito é ilustrado quando um funcionário recebe permissão para usar uma plataforma da empresa?',['Garantia','Bens','Utilidade','Acesso a recursos'],'D','O consumidor recebe acesso aos recursos do provedor conforme condições acordadas.'),
A('Um engenheiro de suporte auxilia um usuário a configurar seu laptop. Qual conceito é exemplificado?',['Transferência de bens','Ações de serviço','Sustentabilidade','Acesso a recursos'],'B','A assistência prestada pelo provedor é uma ação de serviço.'),
A('O que influencia a percepção do consumidor de que um serviço é valioso?',['Custos operacionais mínimos do provedor','Número de provedores','Efeitos positivos superarem os negativos','Investimento do provedor'],'C'),
A('Qual afirmação sobre serviços e resultados desejados é verdadeira?',['Garantem todos os resultados','Eliminam todos os riscos','Sempre têm efeitos positivos','Podem ter resultados inesperados positivos e negativos'],'D'),
A('Uso de componentes recicláveis, redução de carbono e cadeia transparente representa qual conceito?',['Utilidade','Garantia','Experiência do usuário','Sustentabilidade'],'D'),
A('Qual dimensão é influenciada por liderança, segurança psicológica e aprendizado contínuo?',['Parceiros e fornecedores','Fluxos de valor e processos','Informação e tecnologia','Organizações e pessoas'],'D'),
A('Qual dimensão aborda fluxos de trabalho organizacionais e interorganizacionais?',['Parceiros e fornecedores','Informação e tecnologia','Organizações e pessoas','Fluxos de valor e processos'],'D'),
A('Qual dimensão aborda dados e tecnologias usados em produtos e serviços digitais?',['Parceiros e fornecedores','Fluxos de valor e processos','Organizações e pessoas','Informação e tecnologia'],'D'),
A('Qual dimensão trata dos relacionamentos com outras organizações?',['Fluxos de valor e processos','Informação e tecnologia','Parceiros e fornecedores','Organizações e pessoas'],'C'),
A('Segundo “Focar no valor”, a que devem estar vinculadas todas as atividades?',['Benefícios para organização, clientes e stakeholders','Somente receita','Satisfação dos funcionários','Participação de mercado'],'A'),
A('Qual o principal risco de recomeçar sem considerar o que já existe?',['Perder colaboração','Criar complexidade','Não coletar feedback','Desperdiçar tempo, capacidades e recursos existentes'],'D'),
A('Por que usar feedback ao longo das iterações de melhoria?',['Obter unanimidade','Manter ações relevantes e efetivas diante de mudanças','Evitar ajustes futuros','Impedir mudanças de prioridade'],'B'),
A('Qual o risco de desenhar um fluxo considerando todas as exceções possíveis?',['Controle de risco robusto','Complexidade desnecessária','Resultados mais rápidos','Aderência garantida'],'B'),
A('Por que considerar a interação dos Princípios Orientadores?',['São interdependentes e complementares','Um sempre supera os demais','Exigem ordem rígida','Um basta para qualquer situação'],'A'),
A('Qual é o papel do órgão de governança?',['Responsável por desempenho e conformidade no nível mais alto','Operações diárias','Detalhes técnicos','Somente relatórios financeiros'],'A'),
A('Qual NÃO é métrica de sucesso de “Descoberta”?',['Alinhamento estratégico','Relevância de mercado','Desempenho frente ao SLA','Satisfação dos stakeholders'],'C'),
A('O que é um serviço digital?',['Serviço que depende total ou amplamente de produtos digitais','Combinação de recursos tecnológicos','Transferência de bens','Catálogo de serviços'],'A'),
A('O que descreve o que uma organização faz para stakeholders e por quê?',['Fluxo de valor','Cadeia de valor','Modelo operacional','Propósito da organização'],'D'),
A('Como propósito e modelo operacional se relacionam?',['O modelo define estratégia financeira','O propósito diz por que existe; o modelo, como cumpri-lo','O modelo substitui o propósito','Não se relacionam'],'B'),
A('O que descreve uma prática de gerenciamento?',['Série de etapas','Recursos e capacidades para realizar trabalho ou objetivo','Representação visual','Atividades para entregar produtos'],'B'),
A('Qual aspecto do Guia de Práticas descreve papéis, competências e responsabilidades?',['Avaliação de capacidade','Informações gerais','Organizações e pessoas','Parceiros e fornecedores'],'C'),
A('Vincular uma melhoria às metas organizacionais corresponde a qual passo?',['Qual é a visão?','Onde estamos agora?','Aja!','Onde queremos estar?'],'A'),
A('Qual NÃO é passo do mapeamento do fluxo de valor?',['Identificar o fluxo','Mapear estado atual','Mapear estado desejado','Gerenciar o fluxo de valor'],'D'),
A('O que é um produto digital?',['Descrição formal de serviços','Acesso a recursos','Combinação de recursos baseada em tecnologia digital para oferecer valor','Ações de serviço'],'C'),
A('Qual métrica-chave pertence à atividade “Aquisição”?',['Incidentes e desvios','Qualidade de recursos e serviços terceirizados','Desempenho de SLA','Impacto de mudanças'],'B'),
A('Qual relação entre serviços e produtos digitais está correta?',['Produtos baseiam-se sempre em serviços','Serviços digitais baseiam-se em produtos digitais','São independentes','Produtos são ações de serviço'],'B'),
A('Quem assume responsabilidade pelos resultados do consumo de serviços?',['Organização','Patrocinador','Cliente','Provedor'],'C'),
A('Qual relacionamento foca suporte e eficiência com serviços padronizados?',['Básico','Cooperativo','Colaborativo','Parceiro'],'A'),
A('O que é correto sobre a faixa de visibilidade?',['Só atividades do provedor','Só serviços modernos','Aspectos visíveis entre provedor e consumidor','Caminho completo da jornada'],'C'),
A('Qual o propósito principal de “Descoberta”?',['Desenvolver produtos','Alocar recursos','Alinhar capacidades às necessidades e estratégia','Monitorar produtos'],'C'),
A('Qual atividade foca protótipos e especificações?',['Design','Entrega','Suporte','Transição'],'A'),
A('Qual o propósito principal de “Aquisição”?',['Resolver incidentes','Garantir e alocar recursos','Prestar serviços','Criar protótipos'],'B'),
A('Qual atividade minimiza o impacto de incidentes e desastres?',['Transição','Operação','Suporte','Design'],'C'),
A('O que uma especificação de produto descreve?',['Aspectos críticos, requisitos e características','Criação inicial para testes','Capacidade operacional','Integração de código'],'A'),
A('O que é um incidente de TI?',['Mudança significativa','Interrupção não planejada ou redução da qualidade','Causa de interrupções','Vulnerabilidade'],'B'),
A('Como ITIL colabora com DevOps?',['ITIL fornece estrutura; DevOps, práticas e técnicas','Substitui DevOps','Limita DevOps ao software','DevOps governa ITIL'],'A'),
A('Como usar o Modelo de Capacidades de IA do ITIL?',['Comparar ferramentas','Avaliar prontidão e áreas de melhoria','Automatizar governança','Priorizar apenas retorno financeiro'],'B'),
A('O que melhor descreve um SLA?',['Contrato entre fornecedores','Acordo documentado provedor-cliente com serviços e níveis acordados','Discussão informal','Diretriz interna'],'B'),
A('Qual conceito inclui governança, práticas e melhoria contínua?',['Sistema de Valor do ITIL','Entrega e Suporte','Focar no valor','Fluxos e processos'],'A'),
A('Qual o propósito principal do mapeamento do fluxo de valor?',['Automatizar monitoramento','Identificar e priorizar melhorias','Apoiar práticas','Controlar stakeholders'],'B') ]},
{title:'Simulado 2',questions:[
A('Qual o propósito principal de um produto no ITIL?',['Oferecer valor por uma configuração definida de recursos','Substituir práticas de serviço','Facilitar diretamente resultados','Garantir conformidade'],'A'),
A('Qual o principal papel de um serviço digital?',['Definir processos','Habilitar cocriação de valor e resultados','Substituir produto','Garantir conformidade'],'B'),
A('Qual afirmação sobre produto e serviço digital está correta?',['Serviço digital cria valor usando produtos digitais','Produto elimina serviços','Serviço limita-se à TI interna','Serviço independe de produto'],'A'),
A('Impressora entregue com manutenção contínua combina quais interações?',['Acesso e ações','Oferta e ações','Transferência de bens e ações de serviço','Bens e jornada'],'C'),
A('Como o acesso a recursos ajuda na cocriação de valor?',['Permite usar recursos do provedor','Transfere responsabilidade','Limita uso','Substitui ações por automação'],'A'),
A('Qual afirmação sobre cocriação de valor é verdadeira?',['Só o provedor cria','Só o provedor define','Independe das relações','É criada conjuntamente por provedor e consumidor'],'D'),
A('Como utilidade e garantia apoiam valor?',['Custo e risco','Só se aplicam a produtos','Utilidade é uso e garantia é propósito','Utilidade é propósito e garantia é uso'],'D'),
A('Por que considerar resultados, custos e riscos juntos?',['Valor surge com resultados e otimização de custos e riscos','Resultados eliminam riscos','Custos são superiores','Riscos são superiores'],'A'),
A('O que descreve uma jornada de serviço?',['Interações ponta a ponta entre provedor e consumidor','Processos internos','Ciclo do produto','Atividades da cadeia'],'A'),
A('Quem autoriza o orçamento de um serviço?',['Cliente','Usuário','Patrocinador','Fornecedor'],'C'),
A('Qual a maior prioridade da qualidade de serviço?',['Atender requisitos e expectativas acordados','Resolver incidentes rapidamente','Desenvolver rápido','Responsabilidade social'],'A'),
A('O que estabelece entendimento compartilhado da qualidade esperada e alcançada?',['Especificação','SLA','Roadmap','Requisitos de nível'],'B'),
A('Como “informação e tecnologia” apoia o gerenciamento?',['Viabiliza dados, informações e tecnologia para entrega','Define funções','Define fluxos','Gerencia fornecedores'],'A'),
A('Qual dimensão gerencia relações com organizações externas?',['Parceiros e fornecedores','Informação e tecnologia','Organizações e pessoas','Fluxos e processos'],'A'),
A('Por que fluxos de valor e processos são importantes?',['Especificam ferramentas','Mostram coordenação das atividades para criar valor','Definem hierarquias','Descrevem contratos'],'B'),
A('Como organizações e pessoas contribuem?',['Habilidades, cultura e comunicação apoiam valor','Definem tecnologias','Gerenciam externos','Automatizam fluxos'],'A'),
A('Quais são componentes do Sistema de Valor ITIL?',['Fluxos, projetos, releases, incidentes e mudanças','Princípios, governança, descoberta e entrega','Produtos, clientes e fornecedores','Princípios, governança, cadeia de valor, práticas e melhoria contínua'],'D'),
A('Lançar poucas funções, colher feedback e ajustar o próximo release aplica qual princípio?',['Manter simples','Focar no valor','Progredir iterativamente com feedback','Colaborar'],'C'),
A('Como aplicar “Otimizar e automatizar”?',['Substituir pessoas','Otimizar antes de automatizar','Automatizar tudo','Automatizar antes de otimizar'],'B'),
A('O que enfatiza “Pensar e trabalhar holisticamente”?',['Considerar todos os componentes do sistema de valor','Uma equipe responde por melhorias','Toda atividade cria valor','Automatizar tarefas'],'A'),
A('Como aplicar “Colaborar e promover visibilidade”?',['Envolver stakeholders e compartilhar informações','Comunicar só à gerência','Reutilizar processos','Coletar feedback ao final'],'A'),
A('Como aplicar os Princípios Orientadores em conjunto?',['Em sequência fixa','Substituem governança','Independentemente','Coletivamente, equilibrados à situação'],'D'),
A('Qual atividade de governança garante aderência às políticas e direção estratégica?',['Avaliação','Direção','Monitoramento','Descoberta'],'C'),
A('O que faz parte do propósito de “Entrega”?',['Gerenciar onboarding de usuários','Monitorar suporte','Projetar protótipos','Obter recursos'],'A'),
A('Qual atividade mantém e monitora produtos digitais e sistemas de suporte?',['Entrega','Suporte','Operação','Transição'],'C'),
A('Qual atividade introduz produtos novos ou alterados no ambiente de produção?',['Construção','Transição','Entrega','Operação'],'B'),
A('Qual objetivo da atividade “Suporte”?',['Ajudar usuários e manter desempenho','Projetar arquitetura','Construir componentes','Descobrir negócios'],'A'),
A('O que distingue implantação contínua de entrega contínua?',['Evita releases','Exige integração manual','Implanta alterações automaticamente em produção','Elimina testes'],'C'),
A('Qual documento detalha requisitos e características de um produto?',['Requisição de mudança','Requisição de serviço','Protótipo','Especificação do produto'],'D'),
A('O que a observabilidade habilita?',['Entender o sistema por métricas, logs e traces','Aprovar mudanças','Prevenir incidentes','Engenharia de confiabilidade'],'A'),
A('O que é um problema?',['Interrupção não planejada','Causa raiz de um ou mais incidentes','Pedido de acesso','Incidente crítico'],'B'),
A('Qual métrica avalia melhor “Transição”?',['Taxa de sucesso de releases em produção','Ideias geradas','Custo por requisição','Fluxos mapeados'],'A'),
A('Qual métrica avalia melhor “Construção”?',['Incidentes resolvidos','Satisfação do cliente','Requisições no primeiro contato','Qualidade das soluções de produto'],'D'),
A('Como atividades da cadeia apoiam o propósito?',['Transformam intenção estratégica em fluxos coordenados','Definem governança','Padronizam tudo','Definem metas fixas'],'A'),
A('Por que práticas de gerenciamento são importantes?',['Definem propósito','Fornecem capacidades às atividades da cadeia','Impõem ordem fixa','Substituem atividades'],'B'),
A('Por que os Guias de Práticas seguem estrutura padronizada?',['Facilitar entendimento e aplicação','Impor sequência','Impor ferramentas','Limitar flexibilidade'],'A'),
A('Como os Guias beneficiam organizações?',['Prescrevem ferramentas','Separam produto e serviço','Apoiam desenvolvimento de capacidades','Fixam maturidade'],'C'),
A('Por que a melhoria contínua começa pela visão?',['Documentar métricas','Alinhar melhorias aos objetivos','Atribuir ações','Validar iniciativas antigas'],'B'),
A('Como um fluxo de valor habilitador contribui?',['Apoia a operação dos fluxos centrais','Substitui fluxos centrais','Define resultados','É interface principal'],'A'),
A('Qual diferença entre mapear e gerenciar o fluxo de valor?',['Mapear identifica o fluxo; gerenciar mantém seu desempenho','Relatório versus auditoria','Serviço versus produto','Custo versus risco'],'A') ]}
];
